[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "wpycli"
version = "0.1.2"
description = "Cobra-inspired CLI toolkit for Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["wconfig>=0.1.0", "wlogger>=0.1.1"]

[project.scripts]
wpycli = "main:main"

[tool.setuptools]
py-modules = ["main"]

[tool.setuptools.packages.find]
include = ["wpycli*"]

[[tool.uv.index]]
name = "wkqcosoft"
url = "https://pypi.wkqcosoft.cloud"
